class DisassembleRaceCode
  COURSE_CODE_POSITION = (0..1)
  YEAR_CODE_POSITION = (2..3)
  TIMES_CODE_POSITION = 4
  DAY_CODE_POSITION = 5
  NUMBER_OF_RACE_CODE_POSITION = (6..7)
  HORSE_NAME_CODE_POSITION = (8..47)
  HORSE_PEDIGREE_REGISTRATION_CODE_POSITION = (47..55)
  HORSE_NAME_POSITION = (56..91)
  HORSE_GENDER_CODE_POSITION = 92
  HORSE_SYMBOL_CODE_POSITION = (93..94)
  HORSE_BLINKER_CODE_POSITION = 95
  JOCKEY_NAME_POSITION = (96..107)
  JOCKEY_NAME_POSITION = (96..107)
  BURDEN_WEIGHT_POSITION  = (108..110)
  APPRENTICE_CLASS_POSITION = 111
  TRAINER_NAME_POSITION = (113..123)
  TRAINER_BELONG_POSITION
  IDM_POSITION_POSITION
  RISING_DEGREE_POSITION
  ROTATION_POSITION
  LEG_QUALITY_POSITION
  DISTANCE_APTITUDE_POSITION
  DISTANCE_APTITUDE_SECOND_POSITION
  TURF_APTITUDE_CODE_POSITION
  DART_APTITUDE_CODE_POSITION
  HEAVINESS_APTITUDE_CODE_POSITION
  HOOF_CODE_POSITION
  CLASS_CODE_POSITION
  COAT_COLOR_CODE_POSITION
  #他データリンク用キー（OTHER_DATA_LINK_KEY）
  OTHER_DATA_LINK_KEY_PREBIOUS_RUN_1_RACE_SCORE_KEY_POSITION
  OTHER_DATA_LINK_KEY_PREBIOUS_RUN_2_RACE_SCORE_KEY_POSITION
  OTHER_DATA_LINK_KEY_PREBIOUS_RUN_3_RACE_SCORE_KEY_POSITION
  OTHER_DATA_LINK_KEY_PREBIOUS_RUN_4_RACE_SCORE_KEY_POSITION
  OTHER_DATA_LINK_KEY_PREBIOUS_RUN_5_RACE_SCORE_KEY_POSITION
  OTHER_DATA_LINK_KEY_PREBIOUS_RUN_1_RACE_KEY_POSITION
  OTHER_DATA_LINK_KEY_PREBIOUS_RUN_2_RACE_KEY_POSITION
  OTHER_DATA_LINK_KEY_PREBIOUS_RUN_3_RACE_KEY_POSITION
  OTHER_DATA_LINK_KEY_PREBIOUS_RUN_4_RACE_KEY_POSITION
  OTHER_DATA_LINK_KEY_PREBIOUS_RUN_5_RACE_KEY_POSITION
  JOCKEY_CODE_POSITION
  TRAINER_CODE_POSITION
  #賞金情報
  WINNNING_PRIZE_POSITION
  INCOME_PRIZE_POSITION
  CONDITION_CLASS_POSITION

  EXERCISE_POSITION
  BODY_TYPE_POSITION
  BODY_TYPE_TOTAL_1_POSITION
  BODY_TYPE_TOTAL_2_POSITION
  BODY_TYPE_TOTAL_3_POSITION
  HORSE_SPECIAL_MENTION_1_POSITION
  HORSE_SPECIAL_MENTION_2_POSITION
  HORSE_SPECIAL_MENTION_3_POSITION
  #展開予想データ
  EXPANSION_FORECAST_DATA_TEN_INDEX_POSITION
  EXPANSION_FORECAST_DATA_PACE_INDEX_POSITION
  EXPANSION_FORECAST_DATA_RICING_INDEX_POSITION
  EXPANSION_FORECAST_DATA_POSITION_INDEX_POSITION
  HORSE_START_INDEX_POSITION
  HORSE_LAGGING_RATE_POSITION
  RUNNING_BEFORE_REFERENCE_POSITION
  REFERENCE_RIDING_HORSE_CODE_POSITION

  DATA_PARTITION_POSITION
  LEADING_RANK_POSITION
  RESERVE_POSITION

  def initialize(receCode)
    @raceCode = raceCode
  end

  #開催競馬場コードを取得する
  def getRacecourseCode(raceCode)
    raceCode.slice COURSE_CODE_POSITION
  end

  #開催年を取得する
  def getYearCode(raceCode)
    raceCode.slice YEAR_CODE_POSITION
  end

  #競馬場ごとの回を取得する
  def getTimesCode(raceCode)
    raceCode.slice TIMES_CODE_POSITION
  end

  #競馬場ごとの日目を取得する(16進数)
  def getDayCode(raceCode)
    raceCode.slice TIMES_CODE_POSITION
  end

  #馬名キーを取得する
  def getHorse_Name_Code(raceCode)
    raceCode.slice HORSE_NAME_CODE_POSITION
  end

  #血統登録番号を取得する
  def getPedigreeRegistrationCode(raceCode)
    raceCode.slice HORSE_PEDIGREE_REGISTRATION_CODE_POSITION
  end



end