#登録馬データ作成は一旦ペンド
class DisassembleRegisteredHorseCode
  COURSE_CODE_POSITION = (0..1)
  YEAR_CODE_POSITION = (2..3)
  TIMES_CODE_POSITION = 4
  DAY_CODE_POSITION = 5
  NUMBER_OF_RACE_POSITION = (6..7)
  HORSE_NAME_CODE_POSITION = (8..47)
  HORSE_PEDIGREE_REGISTRATION_CODE_POSITION = (47..55)
  HORSE_NAME_POSITION = (56..91)
  HORSE_GENDER_CODE_POSITION = 92
  HORSE_SYMBOL_CODE_POSITION = (93..94)
  BLINKER_CODE_POSITION = 95
  JOCKEY_NAME_POSITION = (96..107)
  BURDEN_WEIGHT_POSITION  = (108..110)
  APPRENTICE_CLASS_POSITION = 111
  TRAINER_NAME_POSITION = (113..123)
  TRAINER_BELONG_POSITION = 0
  IDM_POSITION_POSITION = 0
  RISING_DEGREE_POSITION = 0
  ROTATION_POSITION = 0
  LEG_QUALITY_POSITION = 0
  DISTANCE_APTITUDE_POSITION = 0
  DISTANCE_APTITUDE_SECOND_POSITION = 0
  TURF_APTITUDE_CODE_POSITION = 0
  DART_APTITUDE_CODE_POSITION = 0
  HEAVINESS_APTITUDE_CODE_POSITION = 0
  HOOF_CODE_POSITION = 0
  CLASS_CODE_POSITION = 0
  COAT_COLOR_CODE_POSITION = 0
  #他データリンク用キー（OTHER_DATA_LINK_KEY）
  OTHER_DATA_LINK_KEY_PREBIOUS_RUN_1_RACE_SCORE_KEY_POSITION = 0
  OTHER_DATA_LINK_KEY_PREBIOUS_RUN_2_RACE_SCORE_KEY_POSITION = 0
  OTHER_DATA_LINK_KEY_PREBIOUS_RUN_3_RACE_SCORE_KEY_POSITION = 0
  OTHER_DATA_LINK_KEY_PREBIOUS_RUN_4_RACE_SCORE_KEY_POSITION = 0
  OTHER_DATA_LINK_KEY_PREBIOUS_RUN_5_RACE_SCORE_KEY_POSITION = 0
  OTHER_DATA_LINK_KEY_PREBIOUS_RUN_1_RACE_KEY_POSITION = 0
  OTHER_DATA_LINK_KEY_PREBIOUS_RUN_2_RACE_KEY_POSITION = 0
  OTHER_DATA_LINK_KEY_PREBIOUS_RUN_3_RACE_KEY_POSITION = 0
  OTHER_DATA_LINK_KEY_PREBIOUS_RUN_4_RACE_KEY_POSITION = 0
  OTHER_DATA_LINK_KEY_PREBIOUS_RUN_5_RACE_KEY_POSITION = 0
  JOCKEY_CODE_POSITION = 0
  TRAINER_CODE_POSITION = 0
  #賞金情報
  WINNING_PRIZE_POSITION = 0
  INCOME_PRIZE_POSITION = 0
  CONDITION_CLASS_POSITION = 0

  EXERCISE_POSITION = 0
  BODY_TYPE_POSITION = 0
  BODY_TYPE_TOTAL_1_POSITION = 0
  BODY_TYPE_TOTAL_2_POSITION = 0
  BODY_TYPE_TOTAL_3_POSITION = 0
  HORSE_SPECIAL_MENTION_1_POSITION = 0
  HORSE_SPECIAL_MENTION_2_POSITION = 0
  HORSE_SPECIAL_MENTION_3_POSITION = 0
  #展開予想データ
  EXPANSION_FORECAST_DATA_TEN_INDEX_POSITION = 0
  EXPANSION_FORECAST_DATA_PACE_INDEX_POSITION = 0
  EXPANSION_FORECAST_DATA_RICING_INDEX_POSITION = 0
  EXPANSION_FORECAST_DATA_POSITION_INDEX_POSITION = 0
  HORSE_START_INDEX_POSITION = 0
  HORSE_LAGGING_RATE_POSITION = 0
  RUNNING_BEFORE_REFERENCE_POSITION = 0
  REFERENCE_RIDING_HORSE_CODE_POSITION = 0

  DATA_PARTITION_POSITION = 0
  LEADING_RANK_POSITION = 0
  RESERVE_POSITION = 0

  def initialize(raceCode)
    @raceCode = raceCode
  end

  #開催競馬場コードを取得する
  def getRaceCourseCode
    @raceCode.slice COURSE_CODE_POSITION
  end

  #開催年を取得する
  def getYearCode
    @raceCode.slice YEAR_CODE_POSITION
  end

  #競馬場ごとの回を取得する
  def getTimesCode
    @raceCode.slice TIMES_CODE_POSITION
  end

  #競馬場ごとの日目を取得する(16進数)
  def getDayCode
    @raceCode.slice TIMES_CODE_POSITION
  end

  #レース番号を取得する
  def getNumberOfRace
    @raceCode.slice NUMBER_OF_RACE_POSITION
  end

  #馬名キーを取得する
  def getHorseNameCode
    @raceCode.slice HORSE_NAME_CODE_POSITION
  end

  #血統登録番号を取得する
  def getHorsePedigreeRegsitrationCode
    @raceCode.slice HORSE_PEDIGREE_REGISTRATION_CODE_POSITION
  end

  #馬名を取得する
  def getHorseNamePosition
    @raceCode.slice HORSE_NAME_POSITION
  end

  #馬の性別を取得する
  def getHorseGenderCode
    @raceCode.slice HORSE_GENDER_CODE_POSITION
  end

  #馬記号コードを取得する
  def getHorseSymbolCode
    @raceCode.slice HORSE_SYMBOL_CODE_POSITION
  end

  #ブリンカーコードを取得する
  def getBlinkerCode
    @raceCode.slice BLINKER_CODE_POSITION
  end

  #騎手名を取得する
  def getJockeyName
    @raceCode.slice JOCKEY_NAME_POSITION
  end

end


